### ISSUE TITLE
Enhance Minitest assertions to handle Channel.broadcast_to

### ISSUE THREAD

**Issue by palkan** [palkan/action-cable-testing#11]
The same as #10 but for Minitest

**Comment by TheSmartnik** [comment]
Hi, what enhanced interface should look like?

**Comment by palkan** [comment]
Hi, @TheSmartnik!

I think, adding an optional keyword argument to existing assertions and handling non-string `channel` should work, i.e.:

```ruby
# explicit channel
assert_broadcasts user, 0, channel: NotificationsChannel

# implicit channel
# in that case we can check for `@subscription` presence
# and use its class as channel
assert_broadcasts user, 0
```

See https://github.com/palkan/action-cable-testing/blob/master/lib/rspec/rails/matchers/action_cable.rb#L163
