### ISSUE TITLE
Stub connection is overwrites real connection class

### ISSUE THREAD

**Issue by zhisme** [palkan/action-cable-testing#17]
https://github.com/palkan/action-cable-testing/blob/da049d945f95ca59d485c05a320460e1c6899c23/lib/action_cable/channel/test_case.rb#L43

I have following code:

```
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
      logger.add_tags 'ActionCable', current_user.name
    end

    protected

    def find_verified_user
      verified_user = User.find_by(id: cookies.signed['user.id'])
      if verified_user && cookies.signed['user.expires_at'] > Time.zone.now
        verified_user
      else
        reject_unauthorized_connection
      end
    end
  end
end
```

So for example when I run specs for my channel I expect to my test real connection in application.

But if I have something following in my channel:

```
class TodoChannel < ApplicationCable::Channel
  def subscribed
    stream_from "todo_channel_#{current_user.id}"
  end
end
```

I get following error:

```
Failures:

  1) TodoChannel subscribe 
     Failure/Error: stream_from "todo_channel_#{current_user.id}"
     
     NameError:
       undefined local variable or method `current_user' for #<TodoChannel:0x00007fcf8f17aa00
```

So it comes to that I can't test my connection in application, but instead of it I should write test to a class defined in gem. I think it is not the reason of testing it all.

Maybe we need to use something is like 
pseudo-code
```
if defined?(described_class)
use described_class as stub
....
```
What do you think?

**Comment by palkan** [comment]
Hi @zhisme!

You must specify your identifiers and use explicit `connect` in that case; see https://relishapp.com/palkan/action-cable-testing/docs/channel-specs/channel-spec#specifying-connection-identifiers.

**Comment by zhisme** [comment]
@palkan yeah, you are right.
I get it going with the following code.

```ruby
  let(:user) { create :user }
  subject { subscribe }
  context 'subscribe' do
    before do
      stub_connection current_user: user
    end
    it { is_expected.to be_confirmed }
  end
```
