### ISSUE TITLE
Failing subscription returns nil instead of true

### ISSUE THREAD

**Issue by cickes** [palkan/action-cable-testing#30]
Per the README:
```
it "rejects when no room id" do
    subscribe
    expect(subscription).to be_rejected
end
```
This test fails with the following message:  
```
Failure/Error: expect(subscription).to be_rejected
       expected `#<MyChannel:0x007fb69d350fb0 @connection=#<ActionCable::Channel::ConnectionStub:0x007fb69d351460 ...ue:0>, @reject_subscription=nil, @subscription_confirmation_sent=true, @_streams=["my_channel"]>.rejected?` to return true, got nil
```
Should we be testing for `nil` here instead of `rejected?`?

**Comment by palkan** [comment]
That means that subscription hasn't been rejected.

Could you please share your connection/channel code?

`rejected?` is just an accessor for `@reject_subscription` variable (https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/channel/base.rb#L153), which is `nil` by default.

**Comment by cickes** [comment]
```
#channel  
def subscribed
    stream_from "counts_channel"
end
```

```
#connection
class Connection < ActionCable::Connection::Base
    identified_by :current_token

    def connect
      self.current_token = verify_auth
    end

    def verify_auth
      # use query string token param to verify
    end
end
```

**Comment by palkan** [comment]
You do not reject the subscription, that's why the test is failing.

**Comment by cickes** [comment]
Thank you.  This should have been a connection test checking for a failed connection.  For this to success, the subscription would need to be rejected, as you correctly pointed out.
