### ISSUE TITLE
Run connection test as a part of rspec suite

### ISSUE THREAD

**Issue by archonic** [palkan/action-cable-testing#31]
I've got a working connection rspec file:

```
require "rails_helper"

RSpec.describe ApplicationCable::Connection, type: :channel do
  let!(:au) { create(:accounts_user) }
  let(:account) { au.account }
  let(:user) { au.user }

  it "successfully connects" do
    connect "/ws", cookies: {
      "user.id" => user.id,
      "user.expires_at" => 5.minutes.from_now
    }
    expect(connection.current_user).to eq user
  end

  it "rejects connection" do
    expect { connect "/ws" }.to have_rejected_connection
  end
end
```

But no matter where I place it, it's not running as a part of the whole rspec suite. I've followed the rspec instructions in the readme. Is something missing from those instructions?

**Comment by palkan** [comment]
TBH, doesn't look like something related to action-cable-testing, but anyway: how do you name this file? Could you show me the output of your RSpec command?

**Comment by archonic** [comment]
Sorry, I just needed `_spec.rb` at the end of the file 😅
