### ISSUE TITLE
NotImplementedError on disconnect

### ISSUE THREAD

**Issue by jsgarvin** [palkan/action-cable-testing#37]
I'm getting the following error in my logs when my channel disconnects in a Feature spec.
```
[ActionCable] [user:960328000:tiffany] Finished "/cable/" [WebSocket] for 127.0.0.1 at 2018-12-17 11:44:19 -0700
[ActionCable] [user:960328000:tiffany] There was an exception - NotImplementedError(NotImplementedError)
[ActionCable] [user:960328000:tiffany] /home/jsgarvin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actioncable-5.2.2/lib/action_cable/subscription_adapter/base.rb:22:in `unsubscribe'
`
```
Adding the following method to `ActionCable::SubscriptionAdapter::Test` in a local copy of the gem seems to correct the issue.
```
def unsubscribe(*args)
  #no-op
end
```
I'd be happy to submit a PR with the correction, but there don't seem to be any existing tests around `ActionCable::SubscriptionAdapter::Test`, so I'm not sure how I would go about including a test for it.

**Comment by palkan** [comment]
`:test` adapter is meant to be used with unit-tests, not system tests; that's why it doesn't support subscribing/unsubscribing

try to add `"action_cable/testing/rspec/features"` to your `rails_helper.rb` to use `:async` adapter in features specs (see https://relishapp.com/palkan/action-cable-testing/docs/shared-contexts/action-cable-shared-contexts#require-features-specs-setup)

**Comment by jsgarvin** [comment]
Ah, excellent information. Thank you! However, it turns out that I was still on 0.3.1 :man_facepalming:  of action-cable-testing.  When I updated to 0.3.4 this evening, it all just worked without doing what you suggested above.

So, I did a little digging, and I'm wondering, could https://github.com/palkan/action-cable-testing/commit/71f909a3d82220fe7834ab8bf08d7d96b53acc0b (which was introduced in 0.3.2) be doing for me what you recommended above?  In other words, maybe the test adapter now works with feature specs, free of charge?

I tried adding `action_cable/testing/rspec/features` to the `rails_helper`, but I'm still getting the Test adapter (i.e. this passes. `expect(ActionCable.server.pubsub).to be_a(ActionCable::SubscriptionAdapter::Test)` inside the feature spec.

As I said, it's working now, however, I'd like to know that it's working because it's supposed to be working, and not because I'm inadvertently making use of a genuine "undocumented feature" that's not supported and may disappear.

**Comment by palkan** [comment]
Oh, yeah, you're right, we've added this functionality recently.

> I tried adding action_cable/testing/rspec/features to the rails_helper, but I'm still getting the Test adapter (i.e. this passes. expect(ActionCable.server.pubsub).to be_a(ActionCable::SubscriptionAdapter::Test) inside the feature spec.

Do you have in your RSpec configuration `infer_spec_type_from_location`? We rely on RSpec tags in this feature.

**Comment by jsgarvin** [comment]
As a matter of fact, I do.  Seems to work great.  Thanks.  Sorry for opening a ticket without checking if I was up to date first.  (sigh).
