### ISSUE TITLE
docs about compatibility/how-to-migrate

### ISSUE THREAD

**Issue by namiwang** [palkan/action-cable-testing#38]
I'm so happy that the related codes are finally merged into rails. Thanks for the gem, it's a saver for years.

Currently, I'm using this gem in several projects, I'd like to know if I can migrate to rails and drop one more dependency.

Also, It would be great if someone could note the compability of this gem and anycable somewhere.

Thanks!

**Comment by palkan** [comment]
Hi! Thanks for the feedback!

This functionality will be released in Rails 6 (which first beta is planned for May 2019). So you don't have to migrate to Rails version unless you want to live with Rails 6 alpha)

We'll upgrade this gem as soon as the final testing tools will be merged into Rails (not everything has been merged yet) and RSpec (haven't started this yet).

The upgrade path will be the following:
- upgrade `action-cable-testing` to the version with the Rails-compatible API
- upgrade Rails and remove `action-cable-testing` without changing anything.

Thus our goal is to make this library compatible with the future Rails releases to make upgrade as easy as possible.

**Comment by namiwang** [comment]
@palkan Thanks! BTW what's the compatibility between this gem and anycable?

**Comment by namiwang** [comment]
Thanks!
