### ISSUE TITLE
Readme example issue

### ISSUE THREAD

**Issue by buszu** [palkan/action-cable-testing#49]
Hi!

I've just spotted that in this example from readme you're calling `let(:post)` and then calling `post :create`. I haven't tested this but I believe that `let` will overwrite `post` method so I think the example is incorrect.

```
RSpec.describe CommentsController do
  describe "POST #create" do
    let(:post) { create :post }

    expect { post :create, comment: { text: 'Cool!', post_id: post.id } }.to
      have_broadcasted_to(post).from_channel(PostChannel).with(text: 'Cool!')
  end
end
```

**Comment by sponomarev** [comment]
Hey @buszu! That is a valid point. Thanks for noticing that.

**Comment by palkan** [comment]
Thanks! Fixed
