### ISSUE TITLE
Add ability to match multiple broadcasts

### ISSUE THREAD

**Issue by newyork-anthonyng** [palkan/action-cable-testing#80]
```ruby
def make_multiple_broadcasts
  ActionCable.server.broadcast "user_channel", message: "Hi"
  ActionCable.server.broadcast "user_channel", message: "Bye"
end
```

The above function broadcasts multiple times. Is there a way to test this with `action-cable-testing`, without calling `make_multiple_broadcasts` twice?

**Comment by palkan** [comment]
Do you use RSpec or Minitest?

With RSpec you should be able to combine expectations like this:

```ruby
expect { subject }.to have_broadcasted_to("user_channel").with(message: "Hi").and
  have_broadcated_to("user_channel").with(message: "Bye")
```

With Minitest you should be able to nest `#assert_broadcasts` as well.

**Comment by newyork-anthonyng** [comment]
@palkan Thanks! The `and` worked for my use case.
