### ISSUE TITLE
undefined local variable or method `streams'

### ISSUE THREAD

**Issue by dthomason** [palkan/action-cable-testing#81]
I'm attempting to test the stream in ActionCable with RSpec.  I have the stream working all the way up to the front end but would like a solid test for the streams.  Below is an example of what I'm attempting to do:
```
require 'rails_helper'
RSpec.describe NotificationsChannel, type: :channel do
  it 'successfully subscribes and streams message' do
    user = create(:user)
    stub_connection current_user: user
    subscribe
    key = "my:redis:key"
    $redis.publish(key, 'true')
    expect(subscription).to be_confirmed
    expect(subscription).to have_stream_from key
    expect(streams).to include('true')
  end
end
```
receiving this error
```
NameError:
       undefined local variable or method `streams' for...
```
I have followed all the documentation of adding the `action-cable-testing` gem and its necessary require statement in `rails_helper.rb`

using `Rails 6.0.2.1`

**Comment by palkan** [comment]
> using Rails 6.0.2.1

Then you're using Rails' built-in Action Cable testing tools under the hood.
`streams` method [has been deprecated](https://github.com/palkan/action-cable-testing/blob/f1a0b236e3d94a1a4981fda136625ede6a52a307/lib/action_cable/testing/channel/test_case.rb#L164-L171) and wasn't included into Rails version.

Use `have_stream` matcher instead.

**Comment by dthomason** [comment]
thanks for your response.  I'm actually using rspec for the testing
```
➜ rspec -v
RSpec 3.9
  - rspec-core 3.9.1
  - rspec-expectations 3.9.1
  - rspec-mocks 3.9.1
  - rspec-rails 4.0.0
  - rspec-support 3.9.2
```
But maybe because I'm using Rails 6 it won't work?

I attempted using have_stream(msg) but that is not working either.  Guess I'll do some more digging

**Comment by palkan** [comment]
>  I'm actually using rspec for the testing

RSpec wraps the API provided by Rails (https://github.com/palkan/action-cable-testing/blob/f1a0b236e3d94a1a4981fda136625ede6a52a307/lib/rspec/rails/example/channel_example_group.rb#L25) and defines some additional helpers (https://github.com/palkan/action-cable-testing/blob/f1a0b236e3d94a1a4981fda136625ede6a52a307/lib/rspec/rails/example/channel_example_group.rb#L42-L62).

**Comment by dthomason** [comment]
unfortunately that does not allow me to test the modified data from redis that is then being sent to the consumer, that really only verifies the `key` it's listening to but not the data object being sent.

`expect(streams).to include(the_object_being_sent_to_consumer)` would be ideal

**Comment by palkan** [comment]
You should use [have_broadcasted_to](https://relishapp.com/palkan/action-cable-testing/docs/matchers/have-broadcasted-matcher) matcher for that.
