### ISSUE TITLE
Rails 6.1 support (stop_stream_from)

### ISSUE THREAD

**Issue by jasonatball** [palkan/action-cable-testing#83]
Is this gem still being developed here or has it all moved to the Rails project? Where will Rails 6.1 support be added?

I ask because I ran into this error:
```
     Failure/Error: stop_stream_from uuid
     NoMethodError:
       undefined method `unsubscribe' for nil:NilClass
```
I was able to fix by putting the following at the top of my channel spec:
```
module ActionCable
  module Channel
    class ConnectionStub
      def pubsub
        ActionCable.server.pubsub
      end
    end
  end
end
```

**Comment by palkan** [comment]
> Where will Rails 6.1 support be added?

It should be added to Rails itself. Please, open an issue at http://github.com/rails/rails
